### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ashenAshley** [meltstrap/Caustica#1]
### Image PFPS/posting
Image pfps are something everyone wants. As for image uploading, you COULD have a permission for it like Ciiverse did if you really wanna police shit.
### Working admin panel
bitch ass why does only ciiverse have a working admin panel it's unironically kinda sad that chance makes better admin panels than everyone else
### FIX CSS FIX CSS FIX CSS FIX CSS
padding: 15px 0px 15px 0px; TO #footer IT ISN'T THAT HARD
### footer cloning
whenever post loading occurs, another footer is loaded. you can't see it but if you go about loading a lot of posts it could be a problem
![image of post load fuckery](https://cdn.discordapp.com/attachments/450147226791182337/594627946657087502/unknown.png)

**Comment by That64Boi** [comment]
Add dm's

**Comment by wiredsis** [comment]
Implemented bugfix to footer. Added pfps by default.

**Comment by ashenAshley** [comment]
bitch

**Comment by That64Boi** [comment]
Fix the thing where people don't stay signed in and have to login again after they close the tab.
