### ISSUE TITLE
Logged Out Community View

### ISSUE THREAD

**Issue by ioletsgo** [meltstrap/Caustica#3]
The formatting for the communities are a little bit different if you are logged out, the space where the community posts are supposed to be are shifted to the right, until its nudged on the right of the browser. The image in question was taken on a Chrome laptop.
![image](https://user-images.githubusercontent.com/36903453/62253427-6ec26280-b3bb-11e9-9458-5c953220e3e7.png)

**Comment by BashfulWizard** [comment]
thats nothing to do with logging in or out, its an issue with sessions, you have to refresh the page.
